import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import desktoplight from "../public/images/bg-desktop-light.jpg";
import mobilelight from "../public/images/bg-mobile-light.jpg";

import useWindowSize from "../utils/useWindowSize";
import ToDo from "../components/ToDo";

export default function Home() {
  const size = useWindowSize();

  return (
    <div className="font-josefin ">
      <Head>
        <title>Synebo test task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Bez_nazvanyja_400.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className="bg-lighttheme-VeryLightGray h-full w-full  ">
        {size.width <= 375 ? (
          <>
            <Image className="" src={mobilelight} alt={""} />
          </>
        ) : (
          <Image src={desktoplight} alt={""} />
        )}
        <div className="absolute inset-x-0 top-0 mt-10 xl:mt-20  z-10 flex justify-center items-center">
          <ToDo />
        </div>
      </main>
    </div>
  );
}
